
overrides:
    ceph:
        conf:
            osd:
              osd objectstore: memstore
              memstore device bytes: 100000000
overrides:
  ceph:
    log-whitelist:
      - OSD full dropping all updates

tasks:
    - mds_full:
